### ISSUE TITLE
Development plan

### ISSUE THREAD

**Issue by mihakralj** [mihakralj/QuantLib#10]
@DaveSkender I wanted to share the broader roadmap and vision that I am slowly churning towards.

- **trading assets** - currently dependent on a platform where QuanTAlib runs on, but I have simple classes for YahooFinance, Binance and Oanda half-baked already
- **Indicators** - typically work on one data series (_we are here now_)
- **Signals** - use indicators and generate buy/hold/sell signals (threshold, crossings)
- **Trades** - use signals to generate trade instructions and track drag and commissions 
- **Portfolios** - use trades to generate a re-balanced list of assets (+ cash) owned and track performance
- **Strategy** - a collection of parameters from asset selection to portfolio composition

Success of portfolio is measured by Sharpe or Sortino ratio (or any other performance measures for portfolio); an optimization algo can then fine-tune the _strategy_ to find the highest-yielding portfolio possible within strategy constraints.

For example, a strategy could be defined as:
- **assets:** use US-based ETFs in technology sector
- **indicators:** use family of moving averages + family of oscillators
- **signals:** use a crossover of two MAs + confirmation from an oscillator
- **trades:** no more than 1 trade per day, avoid triggering PDT rule, no shorting
- **portfolios:** keep at least 10 assets in the portfolio, the largest asset cannot be >25% of total value

Strategies should be re-optimized regularly to find the new possible maxima for the porftolio.

**Comment by DaveSkender** [comment]
These are all very cool.  I'm doing much of this in my _private_ trading system, but have started to break these out into discrete modules for separation of concerns.  That's how I started [the indicator library](https://daveskender.github.io/Stock.Indicators).  From an open-source perspective, it's tough to do an all-inclusive platform -- not everyone wants Binance data, for example.

*Signals* + *Trades* combines in two larger features: 1) backtesting and 2) account management.  Backtesting, at least in my system, is just a simulated account.  Portfolio is an overlay on account management for asset allocations, ideally using best practices around risk management.

There's a lot of ocean to boil here, so I'm just taking it slow and trying to mature pieces in a logical order and trying to build them as separate concerns that can be pieced together later (rather than one monolithic app).  I think I'll tackle signals next.  Here's my opinion on what a "full" trading system includes:

- **market data** - there's lots of existing APIs and packages out there, so this is more of a "buy" than "build" for me; though, this can include much more than asset price data (e.g. options data, economic data, sentiment data, etc.)
- **indicators** - prerequisite data for analysis
- **signals and conditions** - defined triggering events and market conditions
- **strategy management** - which combinations of signals define a discrete strategy?
- **backtesting** - of signals and/or strategies, scoring metrics, etc.
- **asset picking** - which symbols are good to use?
- **account management** - trades, margin, and cash management
- **portfolio** - risk management and asset allocation (rebalancing), health metrics
- **charting and visualization** - makes it easier to see what's happening
- **broker integration** - live trading

I have a few other "unique" attributes that I'm happy to share privately.

**Comment by mihakralj** [comment]
@DaveSkender So, we both have indicators 'under control' at the moment (you have 5 times more indicators than me). Are you interested we collaborate on signals, trades and portfolio rebalanging classes? I analyzed what Kevin did in Pandas-TA, and what Oleg is doing in his VectorBT library (both are written in Python). 

If yes, any suggestions how we approach the task?

**Comment by DaveSkender** [comment]
I'm game.  Let's setup a separate GitHub org and have some private team design convos.  You want me to set that up?  I have lots of experience.  We can debate/rename it before we meaningfully rely on any name.

**Comment by mihakralj** [comment]
sounds perfect!

**Comment by DaveSkender** [comment]
I've invited you as a co-Owner.  Once you accept, make your membership "public" (optional) and add yourself to both the `leadership` and `contributors` teams.

Organization-level discussions are enabled and private.  There's a separate `community` team we can use to bring people in who want to participate in our private deliberations.

https://github.com/AlgoNerdLabs
