### ISSUE TITLE
What EMA is the right EMA?

### ISSUE THREAD

**Issue by mihakralj** [mihakralj/QuantLib#11]
@twopirllc and @DaveSkender
I wanted to hear your opinion on how to start the EMA sequence - assuming we don't want to just hide the first n results with NaNs and hope that the sequence will converge sooner than later.

I wrote a short [EMA study](https://github.com/mihakralj/QuanTAlib/blob/dev/docs/ema%20study.ipynb) to document my thinking, but in a nutshell:

- calculating SMA for the first _period_ bars - and then switching to EMA - just feels horribly wrong. Transition from SMA to EMA is unnatural and breaks the continuity. **Bad option**.
- assuming that the previous phantom EMA value was 0 (prev_ema = 0) and calculate EMA that way generates undershooting EMA, requiring long sequence to converge to the real EMA
- assuming that the previous phantom EMA value was the same as the first value (prev_ema = data[0]) generates overshooting EMA, also requires long sequence to converge to the real EMA

There is a method from digital signal processing that can adjust outputs with diminishing attenuation, generating an EMA line that seemingly converges to the real EMA within very samples.

I took a hint from [David Owen's blog](https://blog.fugue88.ws/archives/2017-01/The-correct-way-to-start-an-Exponential-Moving-Average-EMA) and created a new 'Fast-convering EMA' (you can see the algo in the [EMA study](https://github.com/mihakralj/QuanTAlib/blob/dev/docs/ema%20study.ipynb)).

- Blue line: input data signal `{1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0}`
- Upper red line: overshooting EMA(p) (assumes that prev_ema = data[0])
- Lower red line: undershooting EMA(p) (assumes that prev_ema = 0)
- Green Line: SMA(p) followed by EMA(p) - **this is the accepted norm**
- Purple Line: Attenuated, fast-converging EMA(p)

First pic is for p=5, second one is for p=12

![image](https://user-images.githubusercontent.com/31756078/203119978-3aadce20-d852-4047-abc8-1999711bbd04.png)

![image](https://user-images.githubusercontent.com/31756078/203119775-935d6651-ee2a-49c1-86e2-3d855d37f6b6.png)

**Comment by DaveSkender** [comment]
I think there's a whole lot of overfittings scenarios where you can make one of these methods look better than the other.
The only ideal initial value that would decrease convergence time is one that is closest to the unknown actual EMA value -- something you can only get if you have more history.  It's a catch-22.  Any "shoot for the middle" approach, like SMA [or current price] is probably as good as any IMO since you really don't know if price is going up or down.  Starting from `0` seems to make the least sense, since you want that initial value to be near a hypothetically accurate EMA.

To do a true test of methods, you would need to randomize the quote history to generate truly all of the price action scenarios. 
 Maybe try again using your Brownian quotes generator and million iterations?

Curve fitting to a sinewave isn't really much of a test.

**Comment by DaveSkender** [comment]
Random thought: can you transpose the EMA equation and backfill with more accurate values after 100 bars?

**Comment by DaveSkender** [comment]
Another experiment:

- given: `EMA = lastEma + (k * (newValue - lastEma))` and `k = 2 / (n + 1)` where `n` is the lookback period and `i` is the series index
- set `n` dynamically as the minimum of the objective `n` and current `i`, recalculate `k`
- will this overweighting of earlier values leave an initial EMA after `n` periods that is closer than an SMA?

**Comment by twopirllc** [comment]
Hi @mihakralj  and @DaveSkender,

Based on my experience and dabbling in the Technical Arts... the short answer is there is **no** correct _EMA_.


## TA Lib
Given that TA Lib is the _de facto_ library out there, namely due to it's speed, and thus continues to set the standard, the authors also made some bootstrapping/ initializing choices for some indicators. Some of which were dictated by the needs of the current brokerage software (like TradeStation, MetaStock, et al) of that time before halting TA Lib development circa 2013.

According to [TA Lib EMA](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_EMA.c) comment:
```C
 /* The first EMA is calculated differently. It
  * then become the seed for subsequent EMA.
  *
  * The algorithm for this seed vary widely.
  * Only 3 are implemented here:
  *
  * TA_MA_CLASSIC:
  *    Use a simple MA of the first 'period'.
  *    This is the approach most widely documented.
  *
  * TA_MA_METASTOCK:
  *    Use first price bar value as a seed
  *    from the begining of all the available
  *    data.
  *
  * TA_MA_TRADESTATION:
  *    Use 4th price bar as a seed, except when
  *    period is 1 who use 2th price bar or something
  *    like that... (not an obvious one...).
  */
```

## Mathematics

Even in the more rigorous world of Mathematics, _EMA_ can also be calculated differently (with some other descriptions via [wikipedia](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average)).

## Pandas TA

With Pandas TA, one of the primary goals was to implement TA Lib in Python so users would have the same/similar results of TA Lib if they were unable to uninstall TA Lib from source casually. By doing so, I bound my Python calculations to "accurately" match TA Lib by default.

## Final Thoughts

* Clearly there are technically quite a few variations for _EMA_ that could (or should) be implemented. But obviously there is no need to go overboard implementing them all or some variation unless your or your clients require/request them.
* Furthermore since there is an avid population of AI/ML miners, developers and practitioners some indicators could have long periods of initial NaNs in their columns which will eventually force them to drop those rows with _ohlcv_ + _inidicator_ columns with those NaNs before they can do model preprocessing.
   * Not to mention some indicators like **dpo** that can add data leaks due to shifting. So be cognizant of those.
* As you are also aware of convergence, here is TA Libs discussion of [Unstable Period](https://ta-lib.org/d_api/ta_setunstableperiod.html) (if you have not seen already) which some indicators like EMA will have an impact on calculation. I have yet to uncover how to minimize the convergence periods :expressionless:.

Ultimately since TA is the Wild West of Time Series Analysis, I recommend starting with what you deem is "more" accurate and possibly make conditional adjustments (like I have) as needed. 

Hope this helps!

KJ

**Comment by mihakralj** [comment]
> Another experiment:
> 
> * given: `EMA = lastEma + (k * (newValue - lastEma))` and `k = 2 / (n + 1)` where `n` is the lookback period and `i` is the series index
> * set `n` dynamically as the minimum of the objective `n` and current `i`, recalculate `k`
> * will this overweighting of earlier values leave an initial EMA after `n` periods that is closer than an SMA?

I actually tried this - used non-integer n values to fine-tune the k; I got close to the approach how KAMA uses adaptive k.
Covariance of such EMA compared to the original didn't improve much...

**Comment by mihakralj** [comment]
This incongruent field of EMA (and it's derivatives) is killing my validation tests as I don't dare to compare early values of any EMA indicators with - say - @DaveSkender or @twopirllc implementations. Tests are 100% valid after convergence happens, but the early values for this whole family of indicators (EMA, DEMA, TEMA, KAMA, T3, SMMA, ZLEMA...) are incomparable as the algos are not consistent. :(

**Comment by DaveSkender** [comment]
I’m morbidly curious about whether backfilling has any merit, even if repainting.  Or am I just imagining some wishful thinking?  Does this just redraw the exact same data?  :neckbeard: 

`currEma = lastEma + (k * (value - lastEma))`

`currEma = lastEma + k * value - k* lastEma`

`currEma - (k * value) = lastEma * (1 - k)`

`currEma - (k * value) = lastEma * (1 - k)`

`lastEma = (currEma - (k * value)) / (1 - k)`

I think it just redraws it.  All this does is reversed the compute, with equivalent divergence?  Or does it? 😕

Fun thought experiment anyway.  Re-reading the [Wikipedia page](https://en.m.wikipedia.org/wiki/Moving_average#Exponential_moving_average), it does look like there are some recursive methods.

**Comment by mihakralj** [comment]
Few examples of cross-validation that are killing me at the moment:
SMA(5) on a random set - **PASS**:
```
Index     TA-Lib            Skender        Pandas-TA      QuanTAlib
----------------------------------------------------------------------
0            NaN             NaN             NaN          100.572
1            NaN             NaN             NaN          100.263
2            NaN             NaN             NaN           99.658
3            NaN             NaN             NaN           99.595
4         99.697          99.697          99.697           99.697
5         99.409          99.409          99.409           99.409
6         99.220          99.220          99.220           99.220
7         99.503          99.503          99.503           99.503
8         99.711          99.711          99.711           99.711
9         99.665          99.665          99.665           99.665
10        99.845          99.845          99.845           99.845
```
EMA(5) on a random set - **PASS**:
```
Index     TA-Lib            Skender        Pandas-TA      QuanTAlib
----------------------------------------------------------------------
0            NaN             NaN             NaN           99.435
1            NaN             NaN             NaN           99.116
2            NaN             NaN             NaN           99.206
3            NaN             NaN             NaN           99.212
4         99.024          99.024          99.024           99.024
5         99.044          99.044          99.044           99.044
6         98.976          98.976          98.976           98.976
7         99.051          99.051          99.051           99.051
8         99.169          99.169          99.169           99.169
9         99.445          99.445          99.445           99.445
10        99.691          99.691          99.691           99.691
```

DEMA(5) on a random set - **FAIL** - I modeled DEMA by TA-LIB implementation)
```
Index     TA-Lib            Skender        Pandas-TA      QuanTAlib
----------------------------------------------------------------------
0            NaN             NaN             NaN           99.125
1            NaN             NaN             NaN           98.409
2            NaN             NaN             NaN           97.387
3            NaN             NaN             NaN           96.637
4            NaN          96.977          96.977           95.912
5            NaN          95.622          95.622           94.878
6            NaN          95.067          95.067           94.581
7            NaN          94.811          94.811           94.521
8         94.723          94.830          94.830           94.723
9         95.118          95.190          95.190           95.118
10        95.441          95.488          95.488           95.441
11        95.532          95.563          95.563           95.532
12        95.886          95.907          95.907           95.886
13        96.433          96.447          96.447           96.433
14        96.469          96.479          96.479           96.469
15        96.918          96.924          96.924           96.918
16        97.091          97.095          97.095           97.091
17        96.803          96.806          96.806           96.803
18        96.991          96.993          96.993           96.991
19        96.776          96.777          96.777           96.776
```
TEMA(5) on a random set - **FAIL** - I modeled TEMA by Pandas-TA implementation:
```
Index     TA-Lib            Skender        Pandas-TA      QuanTAlib
----------------------------------------------------------------------
0            NaN             NaN             NaN           99.989
1            NaN             NaN             NaN           98.995
2            NaN             NaN             NaN           98.310
3            NaN             NaN             NaN           98.152
4            NaN          98.029          98.029           98.029
5            NaN          97.601          97.601           97.601
6            NaN          97.309          97.309           97.309
7            NaN          96.618          96.618           96.618
8            NaN          96.653          96.653           96.653
9            NaN          96.756          96.756           96.756
10           NaN          97.220          97.220           97.220
11           NaN          97.401          97.401           97.401
12        96.889          96.931          96.931           96.931
13        95.739          95.763          95.763           95.763
14        95.666          95.679          95.679           95.679
15        95.725          95.732          95.732           95.732
16        96.284          96.288          96.288           96.288
17        96.419          96.420          96.420           96.420
18        97.443          97.443          97.443           97.443
19        98.061          98.061          98.061           98.061
```

**Comment by twopirllc** [comment]
@mihakralj 

> This incongruent field of EMA (and it's derivatives) is killing my validation tests with ... the early values for this whole family of indicators (EMA, DEMA, TEMA, KAMA, T3, SMMA, ZLEMA...) are incomparable as the algos are not consistent. :(

Yup! I hear you.

Thanks for sharing the different library validation test results. It's nice to see other non TA Lib calculations.

**Comment by mihakralj** [comment]
> `currEma = lastEma + (k * (value - lastEma))`
> 
> `currEma = lastEma + k * value - k* lastEma`
> 
> `currEma - (k * value) = lastEma * (1 - k)`
> 
> `currEma - (k * value) = lastEma * (1 - k)`
> 
> `lastEma = (currEma - (k * value)) / (1 - k)`

I tried several variations here, all of them just weight differently the currentEma - the same effect could be achieved if we raise the factor `k` up towards 1/2

Which actually begs to try a model for EMA values within the _period_: use a dynamic factor `k` that starts with 1 [for EMA(0)] and progressively slides down towards 2/(period+1) towards EMA(period)

**Comment by DaveSkender** [comment]
> Which actually begs to try a model for EMA values within the period: use a dynamic factor k that starts with 1 [for EMA(0)] and progressively slides down towards 2/(period+1) towards EMA(period)

You’d be getting into adaptive MA world at that point, unrelated to EMA.  Generally, I’m not all that interested in improving that initial incalculable period.  I’d rather have `null` returned than try to fill it.
